name: Project Test

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name : Starting Pipeline
        working-directory: ./project
        run : ls

      - name : Starting Test
        working-directory: ./project
        run : ls